-- ============================================================================
-- Klontonk Dashboard - SKEMA CONTROL PLANE (multi-tenant, 1 project Supabase)
-- ----------------------------------------------------------------------------
-- Cara pakai: Supabase -> SQL Editor -> tempel SELURUH berkas ini -> Run.
-- Aman diulang (idempoten): semua objek memakai IF NOT EXISTS / OR REPLACE /
-- DROP ... IF EXISTS, jadi boleh dijalankan berkali-kali.
--
-- PRASYARAT: db/schema.sql milik klontonk_pos SUDAH dijalankan (tabel tenants,
--   profiles, stock_items, sales, sale_lines, stock_returns harus ada).
--
-- YANG DITAMBAHKAN BERKAS INI:
--   1. clients        - pemilik langganan (pelanggan Anda). 1 client = banyak cabang.
--   2. tenants.client_id - cabang kini milik client (migrasi data otomatis).
--   3. plans          - daftar paket (harga + batas cabang/pengguna).
--   4. subscriptions  - langganan per client (trial/aktif/jatuh tempo).
--   5. platform_admins- akun Anda (vendor), terpisah dari admin client.
--   6. audit_logs     - LOG BISNIS append-only, diisi trigger; client tidak bisa menghapus.
--   7. client_events  - LOG TEKNIS dari aplikasi POS di client (error/gagal simpan).
--   8. Hardening RLS  - can_access_tenant() dikunci ke client_id sehingga admin client A
--                       TIDAK bisa membaca/menghapus data client B.
--   9. Gate langganan - menulis data POS diblokir bila langganan client berakhir.
--
-- CATATAN KEAMANAN
--   * Tidak ada kunci service_role di berkas ini maupun di aplikasi. Keamanan = RLS.
--   * platform_admins TIDAK punya policy INSERT/UPDATE/DELETE: tidak ada yang bisa
--     mempromosikan dirinya jadi superadmin lewat API. Hanya lewat SQL Editor.
--   * audit_logs append-only: hak INSERT/UPDATE/DELETE DICABUT dari authenticated.
--   * Satu fungsi milik klontonk_pos DIGANTI (delete_app_user): versi di bawah ini
--     menambahkan batas client. Selengkapnya lihat komentar bagian 10.
-- ============================================================================

BEGIN;

-- ---------------------------------------------------------------------------
-- 0. Prasyarat
-- ---------------------------------------------------------------------------
DO $$
BEGIN
  IF to_regclass('public.tenants') IS NULL OR to_regclass('public.profiles') IS NULL THEN
    RAISE EXCEPTION 'Jalankan db/schema.sql (klontonk_pos) lebih dulu, lalu jalankan berkas ini.';
  END IF;
END $$;

-- ---------------------------------------------------------------------------
-- 1. clients - pemilik langganan
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.clients (
  id            text PRIMARY KEY CHECK (id ~ '^C[0-9]{4}$'),
  name          text NOT NULL CHECK (char_length(btrim(name)) BETWEEN 2 AND 80),
  contact_name  text CHECK (contact_name IS NULL OR char_length(btrim(contact_name)) <= 60),
  contact_phone text CHECK (contact_phone IS NULL OR contact_phone ~ '^[0-9+ -]{6,24}$'),
  contact_email text CHECK (contact_email IS NULL OR contact_email ~ '^[^@[:space:]]+@[^@[:space:]]+[.][^@[:space:]]+$'),
  note          text CHECK (note IS NULL OR char_length(note) <= 200),
  status        text NOT NULL DEFAULT 'aktif' CHECK (status IN ('aktif','suspend','berhenti')),
  created_at    timestamptz NOT NULL DEFAULT now()
);

CREATE SEQUENCE IF NOT EXISTS public.clients_id_seq AS bigint;

CREATE OR REPLACE FUNCTION public.gen_client_id() RETURNS text
  LANGUAGE plpgsql VOLATILE SET search_path = ''
AS $$
DECLARE
  v_next bigint := nextval('public.clients_id_seq');
BEGIN
  IF v_next > 9999 THEN
    RAISE EXCEPTION 'Batas 9999 client (format id C####) tercapai.' USING ERRCODE = 'P0001';
  END IF;
  RETURN 'C' || lpad(v_next::text, 4, '0');
END $$;

ALTER TABLE public.clients ALTER COLUMN id SET DEFAULT public.gen_client_id();

-- ---------------------------------------------------------------------------
-- 2. plans - daftar paket langganan
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.plans (
  code         text PRIMARY KEY CHECK (code ~ '^[a-z0-9_]{2,20}$'),
  name         text NOT NULL CHECK (char_length(btrim(name)) BETWEEN 2 AND 40),
  price_month  integer NOT NULL DEFAULT 0 CHECK (price_month BETWEEN 0 AND 100000000),
  max_branches integer NOT NULL DEFAULT 1 CHECK (max_branches BETWEEN 1 AND 999),
  max_users    integer NOT NULL DEFAULT 3 CHECK (max_users BETWEEN 1 AND 999),
  is_active    boolean NOT NULL DEFAULT true,
  note         text CHECK (note IS NULL OR char_length(note) <= 200)
);

-- ---------------------------------------------------------------------------
-- 3. subscriptions - langganan per client
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.subscriptions (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_id  text NOT NULL REFERENCES public.clients (id) ON UPDATE CASCADE ON DELETE RESTRICT,
  plan_code  text NOT NULL REFERENCES public.plans (code) ON UPDATE CASCADE ON DELETE RESTRICT,
  started_at date NOT NULL DEFAULT (now() AT TIME ZONE 'Asia/Jakarta')::date,
  expires_at date NOT NULL,
  status     text NOT NULL DEFAULT 'trial' CHECK (status IN ('trial','aktif','jatuh_tempo','berhenti')),
  note       text CHECK (note IS NULL OR char_length(note) <= 200),
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT subscriptions_period_ck CHECK (expires_at >= started_at)
);
CREATE INDEX IF NOT EXISTS subscriptions_client_idx ON public.subscriptions (client_id, expires_at DESC);
CREATE INDEX IF NOT EXISTS subscriptions_expires_idx ON public.subscriptions (expires_at);

-- ---------------------------------------------------------------------------
-- 4. platform_admins - akun vendor (superadmin dashboard)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.platform_admins (
  id         uuid PRIMARY KEY REFERENCES auth.users (id) ON DELETE CASCADE,
  name       text NOT NULL CHECK (char_length(btrim(name)) BETWEEN 1 AND 60),
  created_at timestamptz NOT NULL DEFAULT now()
);-- ---------------------------------------------------------------------------
-- 5. Migrasi cabang: tenants.client_id + data bawaan
--    Semua cabang yang SUDAH ADA dipindahkan ke satu client bawaan (C0001) supaya
--    POS yang sedang jalan TIDAK berubah perilakunya sama sekali.
-- ---------------------------------------------------------------------------
ALTER TABLE public.tenants ADD COLUMN IF NOT EXISTS client_id text;

INSERT INTO public.clients (id, name, note)
VALUES ('C0001', 'Klontonk Internal', 'Client bawaan hasil migrasi: menampung cabang yang sudah ada sebelum dashboard dipasang.')
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.plans (code, name, price_month, max_branches, max_users, note)
VALUES ('internal', 'Internal (non-langganan)', 0, 999, 999, 'Paket bawaan untuk cabang milik sendiri; tanpa batas praktis.')
ON CONFLICT (code) DO NOTHING;

UPDATE public.tenants SET client_id = 'C0001' WHERE client_id IS NULL;

INSERT INTO public.subscriptions (client_id, plan_code, started_at, expires_at, status, note)
SELECT 'C0001', 'internal', (now() AT TIME ZONE 'Asia/Jakarta')::date, DATE '2099-12-31', 'aktif',
       'Langganan bawaan agar POS tetap berjalan tanpa perubahan.'
WHERE NOT EXISTS (SELECT 1 FROM public.subscriptions s WHERE s.client_id = 'C0001');

ALTER TABLE public.tenants ALTER COLUMN client_id SET NOT NULL;

ALTER TABLE public.tenants DROP CONSTRAINT IF EXISTS tenants_client_fk;
ALTER TABLE public.tenants ADD CONSTRAINT tenants_client_fk
  FOREIGN KEY (client_id) REFERENCES public.clients (id) ON UPDATE CASCADE ON DELETE RESTRICT;

CREATE INDEX IF NOT EXISTS tenants_client_idx ON public.tenants (client_id);

-- Sequence id cabang: melanjutkan dari T003 -> T004. Format T### DIPERTAHANKAN karena
-- aplikasi POS memvalidasi /^T\d{3}$/ (js/auth.js) dan db/schema.sql. Batas: 999 cabang.
CREATE SEQUENCE IF NOT EXISTS public.tenants_id_seq AS bigint;

CREATE OR REPLACE FUNCTION public.gen_tenant_id() RETURNS text
  LANGUAGE plpgsql VOLATILE SET search_path = ''
AS $$
DECLARE
  v_next bigint := nextval('public.tenants_id_seq');
BEGIN
  IF v_next > 999 THEN
    RAISE EXCEPTION 'Batas 999 cabang (format id T###) tercapai. Perlu migrasi format id di klontonk_pos dan dashboard.' USING ERRCODE = 'P0001';
  END IF;
  RETURN 'T' || lpad(v_next::text, 3, '0');
END $$;

ALTER TABLE public.tenants ALTER COLUMN id SET DEFAULT public.gen_tenant_id();

-- Samakan posisi sequence dengan data yang sudah ada (id yang diisi manual tidak menaikkan sequence).
SELECT setval('public.tenants_id_seq',
              GREATEST(COALESCE((SELECT max(substring(t.id from 2)::int) FROM public.tenants t), 1), 1),
              (SELECT count(*) FROM public.tenants) > 0);
SELECT setval('public.clients_id_seq',
              GREATEST(COALESCE((SELECT max(substring(c.id from 2)::int) FROM public.clients c), 1), 1),
              (SELECT count(*) FROM public.clients) > 0);

-- ---------------------------------------------------------------------------
-- 6. audit_logs - LOG BISNIS (append-only)
--    Sengaja TANPA foreign key ke clients/tenants: catatan audit harus tetap ada
--    walau data client dihapus, supaya jejak tidak bisa hilang.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.audit_logs (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  at         timestamptz NOT NULL DEFAULT now(),
  actor_id   uuid,
  actor_name text,
  actor_role text,
  client_id  text,
  tenant_id  text,
  action     text NOT NULL CHECK (action ~ '^[a-z][a-z_]*[.][a-z][a-z_]*$'),
  entity     text NOT NULL CHECK (entity ~ '^[a-z][a-z_]*$'),
  entity_id  text,
  detail     jsonb NOT NULL DEFAULT '{}'::jsonb,
  CONSTRAINT audit_logs_detail_size_ck CHECK (pg_column_size(detail) <= 4096)
);
CREATE INDEX IF NOT EXISTS audit_logs_at_idx        ON public.audit_logs (at DESC);
CREATE INDEX IF NOT EXISTS audit_logs_client_at_idx ON public.audit_logs (client_id, at DESC);
CREATE INDEX IF NOT EXISTS audit_logs_tenant_at_idx ON public.audit_logs (tenant_id, at DESC);
CREATE INDEX IF NOT EXISTS audit_logs_action_at_idx ON public.audit_logs (action, at DESC);

-- ---------------------------------------------------------------------------
-- 7. client_events - LOG TEKNIS dari aplikasi POS di client
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.client_events (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  at          timestamptz NOT NULL DEFAULT now(),
  client_id   text,
  tenant_id   text,
  level       text NOT NULL CHECK (level IN ('error','warn','info')),
  source      text NOT NULL CHECK (char_length(source) BETWEEN 1 AND 40),
  message     text NOT NULL CHECK (char_length(message) BETWEEN 1 AND 500),
  context     jsonb NOT NULL DEFAULT '{}'::jsonb,
  app_version text CHECK (app_version IS NULL OR char_length(app_version) <= 20),
  device      text CHECK (device IS NULL OR char_length(device) <= 120),
  CONSTRAINT client_events_context_size_ck CHECK (pg_column_size(context) <= 4096)
);
CREATE INDEX IF NOT EXISTS client_events_at_idx        ON public.client_events (at DESC);
CREATE INDEX IF NOT EXISTS client_events_level_at_idx  ON public.client_events (level, at DESC);
CREATE INDEX IF NOT EXISTS client_events_client_at_idx ON public.client_events (client_id, at DESC);-- ---------------------------------------------------------------------------
-- 8. Helper akses (semua SECURITY DEFINER agar bisa membaca profiles/tenants tanpa
--    terkena RLS-nya sendiri -- pola resmi Supabase untuk memutus rekursi RLS).
-- ---------------------------------------------------------------------------

-- Apakah pemanggil admin platform (vendor)?
CREATE OR REPLACE FUNCTION public.is_superadmin() RETURNS boolean
  LANGUAGE sql STABLE SECURITY DEFINER SET search_path = ''
AS $$ SELECT EXISTS (SELECT 1 FROM public.platform_admins a WHERE a.id = auth.uid()) $$;

-- Client pemilik sebuah cabang.
CREATE OR REPLACE FUNCTION public.tenant_client(p_tenant text) RETURNS text
  LANGUAGE sql STABLE SECURITY DEFINER SET search_path = ''
AS $$ SELECT t.client_id FROM public.tenants t WHERE t.id = p_tenant $$;

-- Client asal pengguna yang login (profil -> cabang -> client).
CREATE OR REPLACE FUNCTION public.app_client_id() RETURNS text
  LANGUAGE sql STABLE SECURITY DEFINER SET search_path = ''
AS $$ SELECT t.client_id FROM public.profiles p JOIN public.tenants t ON t.id = p.tenant_id WHERE p.id = auth.uid() $$;

-- Apakah client pemilik cabang ini punya langganan yang masih berlaku?
CREATE OR REPLACE FUNCTION public.client_active_of_tenant(p_tenant text) RETURNS boolean
  LANGUAGE sql STABLE SECURITY DEFINER SET search_path = ''
AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.subscriptions s
     WHERE s.client_id = public.tenant_client(p_tenant)
       AND s.status IN ('trial', 'aktif')
       AND s.expires_at >= (now() AT TIME ZONE 'Asia/Jakarta')::date
  )
$$;

-- SATU-SATUNYA penentu akses data cabang (dipakai RLS + checkout()/process_return() POS).
--   superadmin   -> semua cabang
--   admin client -> semua cabang MILIK CLIENTNYA SAJA (ini perbaikan kebocoran antar client)
--   kasir        -> hanya cabang tempat ia bertugas
-- Perilaku admin pada data lama TIDAK berubah karena semua cabang lama ada di C0001.
CREATE OR REPLACE FUNCTION public.can_access_tenant(t text) RETURNS boolean
  LANGUAGE sql STABLE SECURITY DEFINER SET search_path = ''
AS $$
  SELECT public.is_superadmin() OR COALESCE((
    SELECT p.tenant_id = t
        OR (p.role = 'admin' AND public.tenant_client(t) IS NOT NULL
            AND public.tenant_client(t) = public.app_client_id())
      FROM public.profiles p WHERE p.id = auth.uid()
  ), false)
$$;

-- Boleh MENULIS data cabang ini? Selain punya akses, langganan client harus masih berlaku.
-- Superadmin dikecualikan supaya Anda tetap bisa ikut memperbaiki data client yang jatuh tempo.
CREATE OR REPLACE FUNCTION public.can_write_tenant(t text) RETURNS boolean
  LANGUAGE sql STABLE SECURITY DEFINER SET search_path = ''
AS $$ SELECT public.can_access_tenant(t) AND (public.is_superadmin() OR public.client_active_of_tenant(t)) $$;

-- ---------------------------------------------------------------------------
-- 9. Pencatat log (client TIDAK boleh memanggilnya langsung)
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.audit_actor_name() RETURNS text
  LANGUAGE sql STABLE SECURITY DEFINER SET search_path = ''
AS $$ SELECT COALESCE((SELECT p.name FROM public.profiles p WHERE p.id = auth.uid()), 'Sistem') $$;

CREATE OR REPLACE FUNCTION public.audit_actor_role() RETURNS text
  LANGUAGE sql STABLE SECURITY DEFINER SET search_path = ''
AS $$ SELECT CASE WHEN public.is_superadmin() THEN 'superadmin'
                 ELSE COALESCE((SELECT p.role FROM public.profiles p WHERE p.id = auth.uid()), 'sistem') END $$;

-- Satu-satunya pintu masuk audit_logs.
CREATE OR REPLACE FUNCTION public.write_audit(
  p_action text, p_entity text, p_entity_id text,
  p_client text, p_tenant text, p_detail jsonb
) RETURNS void
  LANGUAGE sql VOLATILE SECURITY DEFINER SET search_path = ''
AS $$
  INSERT INTO public.audit_logs (actor_id, actor_name, actor_role, client_id, tenant_id, action, entity, entity_id, detail)
  VALUES (auth.uid(), public.audit_actor_name(), public.audit_actor_role(),
          COALESCE(p_client, public.tenant_client(p_tenant)), p_tenant, p_action, p_entity, p_entity_id,
          COALESCE(p_detail, '{}'::jsonb))
$$;-- ---------------------------------------------------------------------------
-- 10. Fungsi trigger LOG BISNIS
--     Dipasang di database, jadi tidak bisa dilewati aplikasi: perubahan stok/harga
--     oleh kasir, akun dibuat/dihapus, penjualan, retur -- semuanya tercatat sendiri.
-- ---------------------------------------------------------------------------

-- Stok & harga (stock_items)
CREATE OR REPLACE FUNCTION public.audit_stock() RETURNS trigger
  LANGUAGE plpgsql SECURITY DEFINER SET search_path = ''
AS $$
DECLARE
  v_detail jsonb;
  v_action text;
  v_tenant text := COALESCE(NEW.tenant_id, OLD.tenant_id);
  v_item   text := COALESCE(NEW.id, OLD.id);
BEGIN
  IF TG_OP = 'INSERT' THEN
    v_action := 'stock.create';
    v_detail := jsonb_build_object('name', NEW.name, 'qty', NEW.qty, 'unit', NEW.unit, 'price', NEW.price, 'barcode', NEW.barcode);
  ELSIF TG_OP = 'UPDATE' THEN
    v_detail := jsonb_strip_nulls(jsonb_build_object(
      'name',    CASE WHEN NEW.name    IS DISTINCT FROM OLD.name    THEN jsonb_build_object('dari', OLD.name,    'jadi', NEW.name)    END,
      'qty',     CASE WHEN NEW.qty     IS DISTINCT FROM OLD.qty     THEN jsonb_build_object('dari', OLD.qty,     'jadi', NEW.qty)     END,
      'unit',    CASE WHEN NEW.unit    IS DISTINCT FROM OLD.unit    THEN jsonb_build_object('dari', OLD.unit,    'jadi', NEW.unit)    END,
      'price',   CASE WHEN NEW.price   IS DISTINCT FROM OLD.price   THEN jsonb_build_object('dari', OLD.price,   'jadi', NEW.price)   END,
      'barcode', CASE WHEN NEW.barcode IS DISTINCT FROM OLD.barcode THEN jsonb_build_object('dari', OLD.barcode, 'jadi', NEW.barcode) END
    ));
    -- Tidak ada perubahan berarti: jangan buat log (menghindari sampah di dashboard).
    IF v_detail = '{}'::jsonb THEN RETURN NEW; END IF;
    v_action := CASE WHEN (v_detail ? 'price') AND NOT (v_detail ? 'qty') THEN 'price.update' ELSE 'stock.update' END;
  ELSE
    v_action := 'stock.delete';
    v_detail := jsonb_build_object('name', OLD.name, 'qty', OLD.qty, 'unit', OLD.unit, 'price', OLD.price);
  END IF;

  PERFORM public.write_audit(v_action, 'stock_items', v_item, NULL, v_tenant, v_detail);
  IF TG_OP = 'DELETE' THEN RETURN OLD; END IF;
  RETURN NEW;
END $$;

-- Akun pengguna (profiles)
CREATE OR REPLACE FUNCTION public.audit_profile() RETURNS trigger
  LANGUAGE plpgsql SECURITY DEFINER SET search_path = ''
AS $$
DECLARE
  v_action text;
  v_detail jsonb;
  v_user   uuid;
  v_tenant text;
  v_name   text;
BEGIN
  IF TG_OP = 'INSERT' THEN
    v_action := 'user.create'; v_user := NEW.id; v_tenant := NEW.tenant_id; v_name := NEW.username;
    v_detail := jsonb_build_object('username', NEW.username, 'name', NEW.name, 'role', NEW.role, 'tenant_id', NEW.tenant_id);
  ELSIF TG_OP = 'UPDATE' THEN
    v_action := 'user.update'; v_user := NEW.id; v_tenant := NEW.tenant_id; v_name := NEW.username;
    v_detail := jsonb_strip_nulls(jsonb_build_object(
      'role',      CASE WHEN NEW.role      IS DISTINCT FROM OLD.role      THEN jsonb_build_object('dari', OLD.role,      'jadi', NEW.role)      END,
      'tenant_id', CASE WHEN NEW.tenant_id IS DISTINCT FROM OLD.tenant_id THEN jsonb_build_object('dari', OLD.tenant_id, 'jadi', NEW.tenant_id) END,
      'name',      CASE WHEN NEW.name      IS DISTINCT FROM OLD.name      THEN jsonb_build_object('dari', OLD.name,      'jadi', NEW.name)      END
    ));
    IF v_detail = '{}'::jsonb THEN RETURN NEW; END IF;
  ELSE
    v_action := 'user.delete'; v_user := OLD.id; v_tenant := OLD.tenant_id; v_name := OLD.username;
    v_detail := jsonb_build_object('username', OLD.username, 'name', OLD.name, 'role', OLD.role, 'tenant_id', OLD.tenant_id);
  END IF;

  PERFORM public.write_audit(v_action, 'profiles', v_name, NULL, v_tenant, v_detail || jsonb_build_object('user_id', v_user));
  IF TG_OP = 'DELETE' THEN RETURN OLD; END IF;
  RETURN NEW;
END $$;

-- Penjualan (sales) dan retur (stock_returns): hanya INSERT yang dicatat (tabel ini append-only).
CREATE OR REPLACE FUNCTION public.audit_sale() RETURNS trigger
  LANGUAGE plpgsql SECURITY DEFINER SET search_path = ''
AS $$
BEGIN
  PERFORM public.write_audit('sale.checkout', 'sales', NEW.no, NULL, NEW.tenant_id,
    jsonb_build_object('total', NEW.total, 'paid', NEW.paid, 'method', NEW.method, 'cashier', NEW.cashier));
  RETURN NEW;
END $$;

CREATE OR REPLACE FUNCTION public.audit_return() RETURNS trigger
  LANGUAGE plpgsql SECURITY DEFINER SET search_path = ''
AS $$
BEGIN
  PERFORM public.write_audit('return.process', 'stock_returns', NEW.no, NULL, NEW.tenant_id,
    jsonb_build_object('kind', NEW.kind, 'name', NEW.name, 'qty', NEW.qty, 'unit', NEW.unit,
                       'amount', NEW.amount, 'reason', NEW.reason, 'cashier', NEW.cashier));
  RETURN NEW;
END $$;-- Perubahan level platform (clients / tenants / plans / subscriptions).
-- Satu fungsi untuk empat tabel: barisnya kecil, jadi isi penuh disimpan sebagai
-- perbandingan sebelum -> sesudah.
CREATE OR REPLACE FUNCTION public.audit_platform() RETURNS trigger
  LANGUAGE plpgsql SECURITY DEFINER SET search_path = ''
AS $$
DECLARE
  v_before jsonb;
  v_after  jsonb;
  v_action text;
  v_entity_id text;
  v_client text;
  v_tenant text;
  v_prefix text;
BEGIN
  v_before := CASE WHEN TG_OP IN ('UPDATE','DELETE') THEN to_jsonb(OLD) END;
  v_after  := CASE WHEN TG_OP IN ('INSERT','UPDATE') THEN to_jsonb(NEW) END;

  v_prefix := CASE TG_TABLE_NAME
                WHEN 'clients'       THEN 'client'
                WHEN 'tenants'       THEN 'branch'
                WHEN 'plans'         THEN 'plan'
                WHEN 'subscriptions' THEN 'subscription'
              END;
  v_action := v_prefix || CASE TG_OP WHEN 'INSERT' THEN '.create' WHEN 'UPDATE' THEN '.update' ELSE '.delete' END;

  IF TG_TABLE_NAME = 'clients' THEN
    v_entity_id := COALESCE(v_after->>'id', v_before->>'id');
    v_client := v_entity_id;
  ELSIF TG_TABLE_NAME = 'tenants' THEN
    v_entity_id := COALESCE(v_after->>'id', v_before->>'id');
    v_client := COALESCE(v_after->>'client_id', v_before->>'client_id');
    v_tenant := v_entity_id;
  ELSIF TG_TABLE_NAME = 'plans' THEN
    v_entity_id := COALESCE(v_after->>'code', v_before->>'code');
  ELSE
    v_entity_id := COALESCE(v_after->>'id', v_before->>'id');
    v_client := COALESCE(v_after->>'client_id', v_before->>'client_id');
  END IF;

  IF TG_OP = 'UPDATE' AND v_before = v_after THEN
    RETURN NEW;
  END IF;

  PERFORM public.write_audit(v_action, TG_TABLE_NAME, v_entity_id, v_client, v_tenant,
    jsonb_build_object('sebelum', v_before, 'sesudah', v_after));

  IF TG_OP = 'DELETE' THEN RETURN OLD; END IF;
  RETURN NEW;
END $$;

-- Pemasangan trigger (DROP IF EXISTS dulu agar aman diulang).
DROP TRIGGER IF EXISTS trg_audit_stock ON public.stock_items;
CREATE TRIGGER trg_audit_stock AFTER INSERT OR UPDATE OR DELETE ON public.stock_items
  FOR EACH ROW EXECUTE FUNCTION public.audit_stock();

DROP TRIGGER IF EXISTS trg_audit_profile ON public.profiles;
CREATE TRIGGER trg_audit_profile AFTER INSERT OR UPDATE OR DELETE ON public.profiles
  FOR EACH ROW EXECUTE FUNCTION public.audit_profile();

DROP TRIGGER IF EXISTS trg_audit_sale ON public.sales;
CREATE TRIGGER trg_audit_sale AFTER INSERT ON public.sales
  FOR EACH ROW EXECUTE FUNCTION public.audit_sale();

DROP TRIGGER IF EXISTS trg_audit_return ON public.stock_returns;
CREATE TRIGGER trg_audit_return AFTER INSERT ON public.stock_returns
  FOR EACH ROW EXECUTE FUNCTION public.audit_return();

DROP TRIGGER IF EXISTS trg_audit_clients ON public.clients;
CREATE TRIGGER trg_audit_clients AFTER INSERT OR UPDATE OR DELETE ON public.clients
  FOR EACH ROW EXECUTE FUNCTION public.audit_platform();

DROP TRIGGER IF EXISTS trg_audit_tenants ON public.tenants;
CREATE TRIGGER trg_audit_tenants AFTER INSERT OR UPDATE OR DELETE ON public.tenants
  FOR EACH ROW EXECUTE FUNCTION public.audit_platform();

DROP TRIGGER IF EXISTS trg_audit_plans ON public.plans;
CREATE TRIGGER trg_audit_plans AFTER INSERT OR UPDATE OR DELETE ON public.plans
  FOR EACH ROW EXECUTE FUNCTION public.audit_platform();

DROP TRIGGER IF EXISTS trg_audit_subscriptions ON public.subscriptions;
CREATE TRIGGER trg_audit_subscriptions AFTER INSERT OR UPDATE OR DELETE ON public.subscriptions
  FOR EACH ROW EXECUTE FUNCTION public.audit_platform();

-- ---------------------------------------------------------------------------
-- 11. Gate langganan: blokir transaksi/retur BARU bila langganan client berakhir.
--     Dipasang sebagai trigger (bukan mengubah isi fungsi POS) karena checkout() dan
--     process_return() SECURITY DEFINER -- keduanya melewati RLS, jadi gate di RLS
--     saja tidak cukup. Data lama tetap bisa dibaca (tidak ada data yang dikunci).
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.enforce_subscription() RETURNS trigger
  LANGUAGE plpgsql SECURITY DEFINER SET search_path = ''
AS $$
BEGIN
  IF public.is_superadmin() THEN RETURN NEW; END IF;
  IF NOT public.client_active_of_tenant(NEW.tenant_id) THEN
    RAISE EXCEPTION 'Masa langganan berakhir. Transaksi baru tidak dapat dicatat -- hubungi penyedia untuk memperpanjang.' USING ERRCODE = 'P0001';
  END IF;
  RETURN NEW;
END $$;

DROP TRIGGER IF EXISTS trg_gate_sale ON public.sales;
CREATE TRIGGER trg_gate_sale BEFORE INSERT ON public.sales
  FOR EACH ROW EXECUTE FUNCTION public.enforce_subscription();

DROP TRIGGER IF EXISTS trg_gate_return ON public.stock_returns;
CREATE TRIGGER trg_gate_return BEFORE INSERT ON public.stock_returns
  FOR EACH ROW EXECUTE FUNCTION public.enforce_subscription();

-- ---------------------------------------------------------------------------
-- 12. Batas paket: jumlah cabang & pengguna mengikuti tabel plans.
--     Paket bawaan "internal" punya batas 999, jadi tidak mengganggu data lama.
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.check_plan_limit() RETURNS trigger
  LANGUAGE plpgsql SECURITY DEFINER SET search_path = ''
AS $$
DECLARE
  v_client text;
  v_plan   public.plans%ROWTYPE;
  v_count  bigint;
BEGIN
  IF TG_TABLE_NAME = 'tenants' THEN
    v_client := NEW.client_id;
  ELSE
    v_client := public.tenant_client(NEW.tenant_id);
  END IF;

  SELECT p.* INTO v_plan
    FROM public.subscriptions s JOIN public.plans p ON p.code = s.plan_code
   WHERE s.client_id = v_client AND s.status IN ('trial','aktif')
     AND s.expires_at >= (now() AT TIME ZONE 'Asia/Jakarta')::date
   ORDER BY s.expires_at DESC LIMIT 1;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Client ini belum punya langganan aktif. Aktifkan langganan lebih dulu.' USING ERRCODE = 'P0001';
  END IF;

  IF TG_TABLE_NAME = 'tenants' THEN
    SELECT count(*) INTO v_count FROM public.tenants t WHERE t.client_id = v_client;
    IF v_count >= v_plan.max_branches THEN
      RAISE EXCEPTION 'Paket "%" hanya mengizinkan % cabang.', v_plan.name, v_plan.max_branches USING ERRCODE = 'P0001';
    END IF;
  ELSE
    SELECT count(*) INTO v_count
      FROM public.profiles p JOIN public.tenants t ON t.id = p.tenant_id
     WHERE t.client_id = v_client;
    IF v_count >= v_plan.max_users THEN
      RAISE EXCEPTION 'Paket "%" hanya mengizinkan % pengguna.', v_plan.name, v_plan.max_users USING ERRCODE = 'P0001';
    END IF;
  END IF;

  RETURN NEW;
END $$;

DROP TRIGGER IF EXISTS trg_plan_limit_branch ON public.tenants;
CREATE TRIGGER trg_plan_limit_branch BEFORE INSERT ON public.tenants
  FOR EACH ROW EXECUTE FUNCTION public.check_plan_limit();

DROP TRIGGER IF EXISTS trg_plan_limit_user ON public.profiles;
CREATE TRIGGER trg_plan_limit_user BEFORE INSERT ON public.profiles
  FOR EACH ROW EXECUTE FUNCTION public.check_plan_limit();-- ---------------------------------------------------------------------------
-- 13. RLS + HARDENING ISOLASI ANTAR CLIENT
--     Sebelum ini: app_role() = 'admin' berarti akses ke SEMUA tenant (satu bisnis).
--     Sesudah ini: admin client hanya clientnya sendiri. Data lama tidak terpengaruh
--     karena seluruh cabang lama berada di satu client (C0001).
-- ---------------------------------------------------------------------------
ALTER TABLE public.clients         ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.plans           ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.subscriptions   ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.platform_admins ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.audit_logs      ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.client_events   ENABLE ROW LEVEL SECURITY;

-- --- profiles: admin client hanya boleh melihat/menyentuh akun satu client ---
DROP POLICY IF EXISTS profiles_read ON public.profiles;
CREATE POLICY profiles_read ON public.profiles FOR SELECT TO authenticated
  USING (id = auth.uid()
         OR public.is_superadmin()
         OR (public.app_role() = 'admin' AND public.tenant_client(tenant_id) = public.app_client_id()));

DROP POLICY IF EXISTS profiles_admin_write ON public.profiles;
CREATE POLICY profiles_admin_write ON public.profiles FOR INSERT TO authenticated
  WITH CHECK (public.is_superadmin()
              OR (public.app_role() = 'admin' AND public.tenant_client(tenant_id) = public.app_client_id()));

DROP POLICY IF EXISTS profiles_admin_update ON public.profiles;
CREATE POLICY profiles_admin_update ON public.profiles FOR UPDATE TO authenticated
  USING (public.is_superadmin()
         OR (public.app_role() = 'admin' AND public.tenant_client(tenant_id) = public.app_client_id()))
  WITH CHECK (public.is_superadmin()
              OR (public.app_role() = 'admin' AND public.tenant_client(tenant_id) = public.app_client_id()));

-- --- tenants: kasir hanya cabangnya, admin client hanya cabang clientnya, superadmin semua ---
DROP POLICY IF EXISTS tenants_read ON public.tenants;
CREATE POLICY tenants_read ON public.tenants FOR SELECT TO authenticated
  USING (public.is_superadmin() OR public.can_access_tenant(id));

DROP POLICY IF EXISTS tenants_admin_insert ON public.tenants;
CREATE POLICY tenants_admin_insert ON public.tenants FOR INSERT TO authenticated
  WITH CHECK (public.is_superadmin());

DROP POLICY IF EXISTS tenants_admin_update ON public.tenants;
CREATE POLICY tenants_admin_update ON public.tenants FOR UPDATE TO authenticated
  USING (public.is_superadmin()) WITH CHECK (public.is_superadmin());

-- --- stock_items: MENULIS ikut terkena gate langganan; membaca tidak dikunci ---
DROP POLICY IF EXISTS stock_insert ON public.stock_items;
CREATE POLICY stock_insert ON public.stock_items FOR INSERT TO authenticated
  WITH CHECK (public.can_write_tenant(tenant_id));

DROP POLICY IF EXISTS stock_update ON public.stock_items;
CREATE POLICY stock_update ON public.stock_items FOR UPDATE TO authenticated
  USING (public.can_write_tenant(tenant_id)) WITH CHECK (public.can_write_tenant(tenant_id));

DROP POLICY IF EXISTS stock_delete ON public.stock_items;
CREATE POLICY stock_delete ON public.stock_items FOR DELETE TO authenticated
  USING (public.can_write_tenant(tenant_id));

-- --- clients ---
DROP POLICY IF EXISTS clients_read ON public.clients;
CREATE POLICY clients_read ON public.clients FOR SELECT TO authenticated
  USING (public.is_superadmin() OR id = public.app_client_id());

DROP POLICY IF EXISTS clients_insert ON public.clients;
CREATE POLICY clients_insert ON public.clients FOR INSERT TO authenticated
  WITH CHECK (public.is_superadmin());

DROP POLICY IF EXISTS clients_update ON public.clients;
CREATE POLICY clients_update ON public.clients FOR UPDATE TO authenticated
  USING (public.is_superadmin()) WITH CHECK (public.is_superadmin());
-- Sengaja TIDAK ada policy DELETE untuk clients: client tidak dihapus keras (pakai kolom status).

-- --- plans: boleh dibaca semua pengguna aktif; hanya superadmin yang mengubah ---
DROP POLICY IF EXISTS plans_read ON public.plans;
CREATE POLICY plans_read ON public.plans FOR SELECT TO authenticated
  USING (public.is_superadmin() OR public.app_role() IS NOT NULL);

DROP POLICY IF EXISTS plans_write ON public.plans;
CREATE POLICY plans_write ON public.plans FOR INSERT TO authenticated WITH CHECK (public.is_superadmin());

DROP POLICY IF EXISTS plans_update ON public.plans;
CREATE POLICY plans_update ON public.plans FOR UPDATE TO authenticated
  USING (public.is_superadmin()) WITH CHECK (public.is_superadmin());

DROP POLICY IF EXISTS plans_delete ON public.plans;
CREATE POLICY plans_delete ON public.plans FOR DELETE TO authenticated USING (public.is_superadmin());

-- --- subscriptions: client boleh melihat masa berlaku dirinya sendiri ---
DROP POLICY IF EXISTS subscriptions_read ON public.subscriptions;
CREATE POLICY subscriptions_read ON public.subscriptions FOR SELECT TO authenticated
  USING (public.is_superadmin() OR client_id = public.app_client_id());

DROP POLICY IF EXISTS subscriptions_write ON public.subscriptions;
CREATE POLICY subscriptions_write ON public.subscriptions FOR INSERT TO authenticated
  WITH CHECK (public.is_superadmin());

DROP POLICY IF EXISTS subscriptions_update ON public.subscriptions;
CREATE POLICY subscriptions_update ON public.subscriptions FOR UPDATE TO authenticated
  USING (public.is_superadmin()) WITH CHECK (public.is_superadmin());

DROP POLICY IF EXISTS subscriptions_delete ON public.subscriptions;
CREATE POLICY subscriptions_delete ON public.subscriptions FOR DELETE TO authenticated USING (public.is_superadmin());

-- --- platform_admins: hanya diri sendiri; TIDAK ada policy tulis (hanya lewat SQL Editor) ---
DROP POLICY IF EXISTS platform_admins_read ON public.platform_admins;
CREATE POLICY platform_admins_read ON public.platform_admins FOR SELECT TO authenticated
  USING (id = auth.uid() OR public.is_superadmin());

-- --- audit_logs: superadmin semua; client hanya jejak miliknya; HANYA BACA ---
DROP POLICY IF EXISTS audit_logs_read ON public.audit_logs;
CREATE POLICY audit_logs_read ON public.audit_logs FOR SELECT TO authenticated
  USING (public.is_superadmin()
         OR public.can_access_tenant(tenant_id)
         OR (tenant_id IS NULL AND client_id IS NOT NULL AND client_id = public.app_client_id()));
-- Sengaja TIDAK ada policy INSERT/UPDATE/DELETE: baris hanya lahir dari trigger SECURITY DEFINER.

-- --- client_events: client boleh KIRIM log teknis untuk cabangnya sendiri ---
DROP POLICY IF EXISTS client_events_read ON public.client_events;
CREATE POLICY client_events_read ON public.client_events FOR SELECT TO authenticated
  USING (public.is_superadmin()
         OR public.can_access_tenant(tenant_id)
         OR (tenant_id IS NULL AND client_id IS NOT NULL AND client_id = public.app_client_id()));

DROP POLICY IF EXISTS client_events_insert ON public.client_events;
CREATE POLICY client_events_insert ON public.client_events FOR INSERT TO authenticated
  WITH CHECK (public.can_access_tenant(tenant_id));
-- Sengaja TIDAK ada policy UPDATE/DELETE: log teknis tidak bisa diubah/dihapus client.-- ---------------------------------------------------------------------------
-- 14. GRANT / REVOKE
-- ---------------------------------------------------------------------------
REVOKE ALL ON public.clients, public.plans, public.subscriptions, public.platform_admins,
              public.audit_logs, public.client_events FROM anon, authenticated;

GRANT SELECT, INSERT, UPDATE ON public.clients TO authenticated;            -- tanpa DELETE (disengaja)
GRANT SELECT, INSERT, UPDATE, DELETE ON public.plans TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.subscriptions TO authenticated;
GRANT SELECT ON public.platform_admins TO authenticated;                    -- policy: hanya barisnya sendiri
GRANT SELECT ON public.audit_logs TO authenticated;                         -- append-only
GRANT SELECT, INSERT ON public.client_events TO authenticated;

-- tenants: POS hanya membaca; hanya superadmin yang menambah/mengubah cabang.
GRANT INSERT, UPDATE ON public.tenants TO authenticated;

-- Sequence untuk pembuatan id otomatis (client & cabang).
GRANT USAGE ON SEQUENCE public.clients_id_seq, public.tenants_id_seq TO authenticated;

REVOKE ALL ON FUNCTION public.gen_client_id(), public.gen_tenant_id() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.gen_client_id(), public.gen_tenant_id() TO authenticated;

REVOKE ALL ON FUNCTION public.is_superadmin(), public.tenant_client(text), public.app_client_id(),
                       public.client_active_of_tenant(text), public.can_write_tenant(text) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.is_superadmin(), public.tenant_client(text), public.app_client_id(),
                     public.client_active_of_tenant(text), public.can_write_tenant(text) TO authenticated;

-- Fungsi internal (hanya dipanggil dari trigger SECURITY DEFINER): tidak untuk siapa pun.
REVOKE ALL ON FUNCTION public.write_audit(text, text, text, text, text, jsonb) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.audit_actor_name(), public.audit_actor_role() FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.audit_stock(), public.audit_profile(), public.audit_sale(), public.audit_return(),
                       public.audit_platform(), public.enforce_subscription(), public.check_plan_limit()
  FROM PUBLIC, anon, authenticated;

-- ---------------------------------------------------------------------------
-- 15. RPC: pembuatan client (client + langganan dalam satu transaksi)
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.create_client_with_plan(
  p_name text,
  p_plan_code text,
  p_contact_name text DEFAULT NULL,
  p_contact_phone text DEFAULT NULL,
  p_contact_email text DEFAULT NULL,
  p_trial_days integer DEFAULT 14,
  p_note text DEFAULT NULL
) RETURNS jsonb
LANGUAGE plpgsql SECURITY DEFINER SET search_path = ''
AS $$
DECLARE
  v_client public.clients%ROWTYPE;
  v_date   date := (now() AT TIME ZONE 'Asia/Jakarta')::date;
BEGIN
  IF NOT public.is_superadmin() THEN
    RAISE EXCEPTION 'Akses ditolak. Fitur ini hanya untuk admin platform.' USING ERRCODE = '42501';
  END IF;
  IF p_trial_days IS NULL OR p_trial_days < 0 OR p_trial_days > 365 THEN
    RAISE EXCEPTION 'Masa trial harus 0 - 365 hari.' USING ERRCODE = '22023';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM public.plans WHERE code = p_plan_code AND is_active) THEN
    RAISE EXCEPTION 'Paket "%" tidak dikenal atau nonaktif.', p_plan_code USING ERRCODE = 'P0001';
  END IF;

  INSERT INTO public.clients (name, contact_name, contact_phone, contact_email, note)
  VALUES (btrim(p_name),
          NULLIF(btrim(COALESCE(p_contact_name, '')), ''),
          NULLIF(btrim(COALESCE(p_contact_phone, '')), ''),
          NULLIF(btrim(COALESCE(p_contact_email, '')), ''),
          NULLIF(btrim(COALESCE(p_note, '')), ''))
  RETURNING * INTO v_client;

  INSERT INTO public.subscriptions (client_id, plan_code, started_at, expires_at, status, note)
  VALUES (v_client.id, p_plan_code, v_date, v_date + p_trial_days,
          CASE WHEN p_trial_days > 0 THEN 'trial' ELSE 'aktif' END,
          'Dibuat otomatis bersama client baru.');

  RETURN to_jsonb(v_client) || jsonb_build_object('trial_days', p_trial_days, 'plan_code', p_plan_code);
END $$;-- ---------------------------------------------------------------------------
-- 16. Hapus akun
--     delete_app_user() adalah fungsi milik klontonk_pos dan DIGANTI di sini:
--     versi aslinya hanya memeriksa app_role() = ''admin'' tanpa batas client, sehingga
--     admin client A bisa menghapus akun milik client B. Versi ini menutup celah itu.
--     Bila db/schema.sql POS diubah, sinkronkan kembali bagian ini.
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.delete_app_user(p_username text) RETURNS void
LANGUAGE plpgsql SECURITY DEFINER SET search_path = ''
AS $$
DECLARE
  v_target public.profiles%ROWTYPE;
  v_actor_client text;
BEGIN
  IF public.app_role() IS DISTINCT FROM 'admin' THEN
    RAISE EXCEPTION 'Akses ditolak. Fitur ini hanya untuk Admin.' USING ERRCODE = '42501';
  END IF;
  SELECT * INTO v_target FROM public.profiles WHERE username = lower(btrim(p_username));
  IF NOT FOUND THEN
    RAISE EXCEPTION 'User tidak ditemukan.' USING ERRCODE = 'P0001';
  END IF;

  v_actor_client := public.app_client_id();
  IF v_actor_client IS NULL
     OR public.tenant_client(v_target.tenant_id) IS DISTINCT FROM v_actor_client THEN
    RAISE EXCEPTION 'Akun itu bukan bagian dari client Anda.' USING ERRCODE = '42501';
  END IF;
  IF v_target.id = auth.uid() THEN
    RAISE EXCEPTION 'Tidak bisa menghapus akun Anda sendiri.' USING ERRCODE = 'P0001';
  END IF;
  IF v_target.role = 'admin' AND (
       SELECT count(*) FROM public.profiles p JOIN public.tenants t ON t.id = p.tenant_id
        WHERE p.role = 'admin' AND t.client_id = v_actor_client) <= 1 THEN
    RAISE EXCEPTION 'Minimal harus ada satu Admin di client ini.' USING ERRCODE = 'P0001';
  END IF;

  DELETE FROM auth.users WHERE id = v_target.id;
END $$;

-- Versi platform: dipakai tombol "Hapus" di dashboard.
CREATE OR REPLACE FUNCTION public.platform_delete_user(p_username text) RETURNS void
LANGUAGE plpgsql SECURITY DEFINER SET search_path = ''
AS $$
DECLARE
  v_target public.profiles%ROWTYPE;
  v_client text;
BEGIN
  IF NOT public.is_superadmin() THEN
    RAISE EXCEPTION 'Akses ditolak. Fitur ini hanya untuk admin platform.' USING ERRCODE = '42501';
  END IF;
  SELECT * INTO v_target FROM public.profiles WHERE username = lower(btrim(p_username));
  IF NOT FOUND THEN
    RAISE EXCEPTION 'User tidak ditemukan.' USING ERRCODE = 'P0001';
  END IF;
  IF v_target.id = auth.uid() THEN
    RAISE EXCEPTION 'Tidak bisa menghapus akun Anda sendiri.' USING ERRCODE = 'P0001';
  END IF;
  v_client := public.tenant_client(v_target.tenant_id);
  IF v_target.role = 'admin' AND (
       SELECT count(*) FROM public.profiles p JOIN public.tenants t ON t.id = p.tenant_id
        WHERE p.role = 'admin' AND t.client_id IS NOT DISTINCT FROM v_client) <= 1 THEN
    RAISE EXCEPTION 'Minimal harus ada satu Admin di client ini.' USING ERRCODE = 'P0001';
  END IF;

  DELETE FROM auth.users WHERE id = v_target.id;
END $$;

-- ---------------------------------------------------------------------------
-- 17. Titik masuk log dari aplikasi
--     Dipakai klontonk_pos: rpc(''log_event'', { p_action: ''auth.login'' })
--     dan rpc(''report_event'', { ... }) untuk error teknis di perangkat.
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.log_event(p_action text, p_detail jsonb DEFAULT '{}'::jsonb)
RETURNS void
LANGUAGE plpgsql SECURITY DEFINER SET search_path = ''
AS $$
DECLARE
  v_tenant text := (SELECT p.tenant_id FROM public.profiles p WHERE p.id = auth.uid());
BEGIN
  IF v_tenant IS NULL THEN RETURN; END IF;
  IF p_action IS NULL OR p_action NOT LIKE '%.%' THEN
    RAISE EXCEPTION 'Nama aksi harus berbentuk "kategori.aksi".' USING ERRCODE = '22023';
  END IF;
  PERFORM public.write_audit(p_action, 'auth', NULL, NULL, v_tenant, COALESCE(p_detail, '{}'::jsonb));
END $$;

CREATE OR REPLACE FUNCTION public.report_event(
  p_level text, p_source text, p_message text,
  p_context jsonb DEFAULT '{}'::jsonb, p_app_version text DEFAULT NULL
) RETURNS void
LANGUAGE plpgsql SECURITY DEFINER SET search_path = ''
AS $$
DECLARE
  v_tenant text := (SELECT p.tenant_id FROM public.profiles p WHERE p.id = auth.uid());
  v_level  text := CASE WHEN p_level IN ('error','warn','info') THEN p_level ELSE 'error' END;
BEGIN
  IF v_tenant IS NULL THEN RETURN; END IF;
  INSERT INTO public.client_events (client_id, tenant_id, level, source, message, context, app_version)
  VALUES (public.tenant_client(v_tenant), v_tenant, v_level,
          left(COALESCE(NULLIF(btrim(p_source), ''), 'app'), 40),
          left(COALESCE(NULLIF(btrim(p_message), ''), '(tanpa pesan)'), 500),
          COALESCE(p_context, '{}'::jsonb),
          left(p_app_version, 20));
END $$;-- ---------------------------------------------------------------------------
-- 18. RPC pendukung dashboard
-- ---------------------------------------------------------------------------
-- Ringkasan pemakaian harian satu client (halaman Pemakaian).
CREATE OR REPLACE FUNCTION public.usage_daily(p_client text, p_from date, p_to date)
RETURNS TABLE (
  day date, trx_count bigint, trx_total bigint,
  return_count bigint, return_amount bigint,
  event_count bigint, log_count bigint
)
LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path = ''
AS $$
DECLARE
  v_from date := COALESCE(p_from, (now() AT TIME ZONE 'Asia/Jakarta')::date - 29);
  v_to   date := COALESCE(p_to, (now() AT TIME ZONE 'Asia/Jakarta')::date);
BEGIN
  IF NOT (public.is_superadmin() OR p_client = public.app_client_id()) THEN
    RAISE EXCEPTION 'Akses ditolak.' USING ERRCODE = '42501';
  END IF;

  RETURN QUERY
  WITH t AS (SELECT tn.id FROM public.tenants tn WHERE tn.client_id = p_client),
       d AS (SELECT g::date AS d_day FROM generate_series(v_from, v_to, interval '1 day') g)
  SELECT d.d_day,
         (SELECT count(*) FROM public.sales s WHERE s.tenant_id IN (SELECT id FROM t)
            AND (s.at AT TIME ZONE 'Asia/Jakarta')::date = d.d_day)::bigint,
         (SELECT COALESCE(sum(s.total), 0) FROM public.sales s WHERE s.tenant_id IN (SELECT id FROM t)
            AND (s.at AT TIME ZONE 'Asia/Jakarta')::date = d.d_day)::bigint,
         (SELECT count(*) FROM public.stock_returns r WHERE r.tenant_id IN (SELECT id FROM t)
            AND (r.at AT TIME ZONE 'Asia/Jakarta')::date = d.d_day)::bigint,
         (SELECT COALESCE(sum(r.amount), 0) FROM public.stock_returns r WHERE r.tenant_id IN (SELECT id FROM t)
            AND (r.at AT TIME ZONE 'Asia/Jakarta')::date = d.d_day)::bigint,
         (SELECT count(*) FROM public.client_events e WHERE e.client_id = p_client
            AND (e.at AT TIME ZONE 'Asia/Jakarta')::date = d.d_day)::bigint,
         (SELECT count(*) FROM public.audit_logs a WHERE a.client_id = p_client
            AND (a.at AT TIME ZONE 'Asia/Jakarta')::date = d.d_day)::bigint
    FROM d
   ORDER BY d.d_day;
END $$;

-- Pemangkas log (Free plan hanya 500 MB). Retensi minimal 30 hari audit / 7 hari log teknis.
CREATE OR REPLACE FUNCTION public.purge_old_logs(p_audit_days integer DEFAULT 180, p_event_days integer DEFAULT 60)
RETURNS jsonb
LANGUAGE plpgsql SECURITY DEFINER SET search_path = ''
AS $$
DECLARE
  v_audit  bigint := 0;
  v_events bigint := 0;
BEGIN
  IF NOT public.is_superadmin() THEN
    RAISE EXCEPTION 'Akses ditolak. Fitur ini hanya untuk admin platform.' USING ERRCODE = '42501';
  END IF;
  IF p_audit_days IS NULL OR p_event_days IS NULL OR p_audit_days < 30 OR p_event_days < 7 THEN
    RAISE EXCEPTION 'Retensi minimal 30 hari (log audit) dan 7 hari (log teknis).' USING ERRCODE = '22023';
  END IF;

  DELETE FROM public.audit_logs WHERE at < now() - make_interval(days => p_audit_days);
  GET DIAGNOSTICS v_audit = ROW_COUNT;
  DELETE FROM public.client_events WHERE at < now() - make_interval(days => p_event_days);
  GET DIAGNOSTICS v_events = ROW_COUNT;

  RETURN jsonb_build_object('audit_deleted', v_audit, 'events_deleted', v_events);
END $$;

-- ---------------------------------------------------------------------------
-- 19. View ringkasan per client (halaman Ringkasan & Pemakaian)
--     security_invoker = true -> RLS tabel dasar tetap berlaku untuk pemanggil,
--     sehingga client hanya melihat datanya sendiri. Butuh PostgreSQL 15+ (Supabase 15/17).
-- ---------------------------------------------------------------------------
CREATE OR REPLACE VIEW public.v_client_overview WITH (security_invoker = true) AS
SELECT
  c.id,
  c.name,
  c.status,
  c.contact_name,
  c.contact_phone,
  c.contact_email,
  c.note,
  (SELECT count(*) FROM public.tenants t WHERE t.client_id = c.id) AS branch_count,
  (SELECT count(*) FROM public.profiles p JOIN public.tenants t ON t.id = p.tenant_id
    WHERE t.client_id = c.id) AS user_count,
  s.plan_code,
  pl.name AS plan_name,
  pl.price_month,
  s.status AS sub_status,
  s.started_at,
  s.expires_at,
  CASE WHEN s.expires_at IS NULL THEN NULL
       ELSE (s.expires_at - (now() AT TIME ZONE 'Asia/Jakarta')::date) END AS days_left,
  COALESCE((SELECT count(*) FROM public.sales sa JOIN public.tenants t ON t.id = sa.tenant_id
     WHERE t.client_id = c.id AND sa.at >= now() - interval '30 days'), 0) AS trx_30d,
  COALESCE((SELECT sum(sa.total) FROM public.sales sa JOIN public.tenants t ON t.id = sa.tenant_id
     WHERE t.client_id = c.id AND sa.at >= now() - interval '30 days'), 0) AS omzet_30d,
  COALESCE((SELECT count(*) FROM public.client_events e
     WHERE e.client_id = c.id AND e.at >= now() - interval '7 days'), 0) AS events_7d,
  COALESCE((SELECT count(*) FROM public.client_events e
     WHERE e.client_id = c.id AND e.level = 'error' AND e.at >= now() - interval '7 days'), 0) AS errors_7d,
  COALESCE((SELECT count(*) FROM public.audit_logs a
     WHERE a.client_id = c.id AND a.at >= now() - interval '7 days'), 0) AS logs_7d
FROM public.clients c
LEFT JOIN LATERAL (
  SELECT s2.* FROM public.subscriptions s2
   WHERE s2.client_id = c.id
   ORDER BY (s2.status IN ('trial', 'aktif')) DESC, s2.expires_at DESC
   LIMIT 1
) s ON true
LEFT JOIN public.plans pl ON pl.code = s.plan_code;

-- ---------------------------------------------------------------------------
-- 20. GRANT untuk RPC baru
-- ---------------------------------------------------------------------------
REVOKE ALL ON FUNCTION public.create_client_with_plan(text, text, text, text, text, integer, text),
                       public.platform_delete_user(text), public.usage_daily(text, date, date),
                       public.purge_old_logs(integer, integer), public.log_event(text, jsonb),
                       public.report_event(text, text, text, jsonb, text)
  FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.create_client_with_plan(text, text, text, text, text, integer, text),
                            public.platform_delete_user(text), public.usage_daily(text, date, date),
                            public.purge_old_logs(integer, integer), public.log_event(text, jsonb),
                            public.report_event(text, text, text, jsonb, text)
  TO authenticated;

REVOKE ALL ON public.v_client_overview FROM anon;
GRANT SELECT ON public.v_client_overview TO authenticated;

COMMIT;

-- ============================================================================
-- SELESAI. Langkah setelah menjalankan berkas ini:
--   1. Buat akun admin platform: Supabase -> Authentication -> Add user (email + password).
--   2. Daftarkan akun itu sebagai superadmin (ganti emailnya):
--        INSERT INTO public.platform_admins (id, name)
--        SELECT id, 'Nama Anda' FROM auth.users WHERE email = 'admin@contoh.com';
--   3. Jalankan db/verify.sql (dan db/verify-rls.sql) untuk memastikan semua terpasang.
--   4. Wajib: Authentication -> Providers -> Email -> "Confirm email" DIMATIKAN,
--      supaya akun client buatan dashboard (username@klontonk.local) bisa langsung login.
-- ============================================================================